/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VideoClub;

/**
 *
 * @author casco
 */
import Clases.Pelicula;
import Clases.Genero;
import javax.swing.table.DefaultTableModel;

public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    Pelicula pelicula = new Pelicula();
    Genero genero = new Genero();

    public Pantalla() {
        initComponents();

        tabla.setModel(pelicula.mostrar());
        String numero;
        genero2.addItem("-");
        for (int i = 0; i < genero.mostrar().size(); i++) {
            genero3.addItem(genero.mostrar().get(i).toString());
            genero2.addItem(genero.mostrar().get(i).toString());
        }
        for (int i = 0; i < 131; i++) {
            numero = String.valueOf(i);
            edadmin.addItem(numero);
        }
        for (int i = 0; i < 601; i++) {
            numero = String.valueOf(i);
            duracion.addItem(numero);
            tiempo2.addItem(numero);
        }
        for (int i = 0; i < 19; i++) {
            numero = String.valueOf(i);
            edadmin2.addItem(numero);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titulo = new javax.swing.JTextField();
        genero3 = new javax.swing.JComboBox<>();
        duracion = new javax.swing.JComboBox<>();
        edadmin = new javax.swing.JComboBox<>();
        anadir = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        tiempo2 = new javax.swing.JComboBox<>();
        edadmin2 = new javax.swing.JComboBox<>();
        genero2 = new javax.swing.JComboBox<>();
        anadir1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        usuario1 = new javax.swing.JLabel();
        usuario2 = new javax.swing.JLabel();
        usuario3 = new javax.swing.JLabel();
        usuario4 = new javax.swing.JLabel();
        usuario5 = new javax.swing.JLabel();
        usuario6 = new javax.swing.JLabel();
        usuario7 = new javax.swing.JLabel();
        usuario8 = new javax.swing.JLabel();
        usuario9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadminActionPerformed(evt);
            }
        });

        anadir.setText("Añadir");
        anadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                anadirMouseReleased(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.setEnabled(false);
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eliminarMouseReleased(evt);
            }
        });
        eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eliminarKeyReleased(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.setEnabled(false);
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                modificarMouseReleased(evt);
            }
        });
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        genero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genero2ActionPerformed(evt);
            }
        });

        anadir1.setText("Recomendar");
        anadir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                anadir1MouseReleased(evt);
            }
        });
        anadir1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anadir1KeyReleased(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tabla);

        usuario1.setText("Duracion");

        usuario2.setText("Titulo");

        usuario3.setText("Edad Minima");

        usuario4.setText("Genero");

        usuario5.setText("Recomendar");

        usuario6.setText("Tiempo");

        usuario7.setText("Edad menor");

        usuario8.setText("Genero");

        usuario9.setText("Pelicula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anadir)
                                .addGap(59, 59, 59)
                                .addComponent(modificar)
                                .addGap(61, 61, 61)
                                .addComponent(eliminar))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(usuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(genero3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(usuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anadir1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(usuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edadmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(usuario8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(genero2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(usuario9)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario1)
                    .addComponent(usuario3)
                    .addComponent(usuario2)
                    .addComponent(usuario4))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anadir)
                    .addComponent(eliminar)
                    .addComponent(modificar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadmin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(anadir1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void genero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genero2ActionPerformed

    private void anadirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadirMouseReleased
        // TODO add your handling code here:
        if (!titulo.getText().isEmpty() && duracion.getSelectedItem() != null && edadmin.getSelectedItem() != null && genero3.getSelectedItem() != null) {
            pelicula.anadir(titulo.getText(), duracion.getSelectedItem(), edadmin.getSelectedItem(), genero3.getSelectedItem());
            tabla.setModel(pelicula.mostrar());
            titulo.setText("");
            duracion.setSelectedIndex(0);
            edadmin.setSelectedIndex(0);
            genero3.setSelectedIndex(0);
        } else {
            System.out.println("No se han introducido todos los valores");
        }
    }//GEN-LAST:event_anadirMouseReleased

    private void edadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadminActionPerformed

    private void tablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseReleased
        // TODO add your handling code here:
        if (tabla.getSelectedRow() != -1) {
            eliminar.setEnabled(true);
            modificar.setEnabled(true);
            String nombreEdicion = (String) tabla.getValueAt(tabla.getSelectedRow(), 0);
            int duracionEdicion = (Integer) tabla.getValueAt(tabla.getSelectedRow(), 1);
            int edadminimaEdicion = (Integer) tabla.getValueAt(tabla.getSelectedRow(), 2);
            String generoEdicion = (String) tabla.getValueAt(tabla.getSelectedRow(), 3);
            titulo.setText(nombreEdicion);
            duracion.setSelectedIndex(duracionEdicion);
            edadmin.setSelectedIndex(edadminimaEdicion);
            genero3.setSelectedItem(generoEdicion);
        }
    }//GEN-LAST:event_tablaMouseReleased

    private void modificarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseReleased
        // TODO add your handling code here:
        String nombreEdicion = (String) tabla.getValueAt(tabla.getSelectedRow(), 0);
        String nombre = titulo.getText();
        Object duracion2 = duracion.getSelectedIndex();
        Object edad2 = edadmin.getSelectedIndex();
        Object genero2 = genero3.getSelectedItem();
        pelicula.modificar(nombre, duracion2, edad2, genero2, nombreEdicion);
        tabla.setModel(pelicula.mostrar());
        eliminar.setEnabled(false);
        modificar.setEnabled(false);
        titulo.setText("");
        duracion.setSelectedIndex(0);
        edadmin.setSelectedIndex(0);
        genero3.setSelectedIndex(0);
    }//GEN-LAST:event_modificarMouseReleased

    private void eliminarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_eliminarKeyReleased

    private void anadir1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anadir1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_anadir1KeyReleased

    private void eliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseReleased
        // TODO add your handling code here:
        if (tabla.getSelectedRow() != -1) {
            String nombre = titulo.getText();
            Object duracion2 = duracion.getSelectedIndex();
            Object edad = edadmin.getSelectedIndex();
            Object genero4 = genero3.getSelectedItem();
            pelicula.eliminar(nombre, duracion2, edad, genero4);
            tabla.setModel(pelicula.mostrar());
            eliminar.setEnabled(false);
            modificar.setEnabled(false);
            titulo.setText("");
            duracion.setSelectedIndex(0);
            edadmin.setSelectedIndex(0);
            genero3.setSelectedIndex(0);
        }
    }//GEN-LAST:event_eliminarMouseReleased

    private void anadir1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadir1MouseReleased
        // TODO add your handling code here:
        int tiemporecomendar = (Integer) tiempo2.getSelectedIndex();
        int edadminimarecomendar = (Integer) edadmin2.getSelectedIndex();
        String generorecomendar = (String) genero2.getSelectedItem();
        jTable2.setModel(pelicula.recomendar(tiemporecomendar, edadminimarecomendar, generorecomendar));
        tiempo2.setSelectedIndex(0);
        edadmin2.setSelectedIndex(0);
        genero2.setSelectedIndex(0);
    }//GEN-LAST:event_anadir1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadir;
    private javax.swing.JButton anadir1;
    private javax.swing.JComboBox<String> duracion;
    private javax.swing.JComboBox<String> edadmin;
    private javax.swing.JComboBox<String> edadmin2;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox<String> genero2;
    private javax.swing.JComboBox<String> genero3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tiempo2;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    private javax.swing.JLabel usuario3;
    private javax.swing.JLabel usuario4;
    private javax.swing.JLabel usuario5;
    private javax.swing.JLabel usuario6;
    private javax.swing.JLabel usuario7;
    private javax.swing.JLabel usuario8;
    private javax.swing.JLabel usuario9;
    // End of variables declaration//GEN-END:variables
}
